import os
import secrets
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_EXAMPLE = ROOT / ".env.example"
ENV_FILE = ROOT / ".env"


def _parse_env_lines(text: str):
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, val = line.split("=", 1)
        yield key.strip(), val.strip()


def _format_env(k: str, v: str) -> str:
    # keep simple and safe; quote only if needed
    if any(c in v for c in [" ", "#"]):
        v = v.replace('"', '\\"')
        return f'{k}="{v}"'
    return f"{k}={v}"


def main() -> int:
    if not ENV_EXAMPLE.exists():
        raise SystemExit(f"Missing {ENV_EXAMPLE}")

    example_text = ENV_EXAMPLE.read_text(encoding="utf-8")
    example_keys = [k for k, _ in _parse_env_lines(example_text)]

    current = {}
    if ENV_FILE.exists():
        current_text = ENV_FILE.read_text(encoding="utf-8")
        current = {k: v for k, v in _parse_env_lines(current_text)}

    out = {}
    # keep existing values if already set
    out.update(current)

    def ensure(key: str, value: str):
        if out.get(key, "") == "":
            out[key] = value

    # defaults
    ensure("APP_ENV", "local")
    ensure("APP_DEBUG", "0")
    ensure("SESSION_SAMESITE", "Lax")

    ensure("DB_HOST", "localhost")
    ensure("DB_PORT", "3306")
    ensure("DB_NAME", "gtorg_xeyal")
    ensure("DB_USER", "root")
    ensure("DB_PASSWORD", "")
    ensure("DB_CHARSET", "utf8mb4")

    # secrets
    ensure("FLASK_SECRET_KEY", secrets.token_urlsafe(48))
    ensure("ADMIN_BOOTSTRAP_TOKEN", secrets.token_urlsafe(32))

    # keep bootstrap disabled by default
    ensure("ALLOW_ADMIN_BOOTSTRAP", "0")
    ensure("ADMIN_USERNAME", "admin")
    ensure("ADMIN_EMAIL", "admin@ostwindgroup.com")
    ensure("ADMIN_PASSWORD", "")

    # optional integrations
    ensure("TELEGRAM_BOT_TOKEN", "")
    ensure("TELEGRAM_CHAT_ID", "")

    # write only keys that exist in example, plus any already present in .env
    ordered = []
    seen = set()
    for k in example_keys:
        if k in out:
            ordered.append((k, out[k]))
            seen.add(k)
    # keep extra keys (if any) at end
    for k in sorted(out.keys()):
        if k not in seen:
            ordered.append((k, out[k]))

    content = "# Generated by scripts/setup_env.py (DO NOT COMMIT)\n\n"
    for k, v in ordered:
        content += _format_env(k, v) + "\n"

    ENV_FILE.write_text(content, encoding="utf-8")
    print("Created/updated .env (secrets generated, not printed).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

